name: Deploy Frontend Prefeitura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - run: |
          docker build -t devnardi/web-prefeitura:latest .
          docker push devnardi/web-prefeitura:latest

      - run: |
          docker rm -f web-prefeitura || true
          docker pull devnardi/web-prefeitura:latest
          docker run -d \
            --name web-prefeitura \
            -p 3000:3000 \
            --user 1001:1001 \
            --read-only \
            --cap-drop ALL \
            --security-opt no-new-privileges \
            -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            devnardi/web-prefeitura:latest
